export { default as Tab, type TabProps } from "./Tab.svelte"
export { default as TabGroup, type TabGroupProps } from "./TabGroup.svelte"
export { default as TabList, type TabListProps } from "./TabList.svelte"
export { default as TabPanel, type TabPanelProps } from "./TabPanel.svelte"
export { default as TabPanels, type TabPanelsProps } from "./TabPanels.svelte"
